version: "3"
services:
  guacdb:
    container_name: guacamoledb
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: "${POSTGRES_NAME:-guacamole_db}"
      POSTGRES_USER: "${GUACAMOLE_DB_USER:-guacamole_db_user}"
      POSTGRES_PASSWORD: "${GUACAMOLE_DB_PASS:-weakpass}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - guacamole_network
  guacd:
    container_name: guacd
    image: guacamole/guacd
    restart: unless-stopped
    networks:
      - guacamole_network
  guacamole:
    container_name: guacamole
    image: guacamole/guacamole
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: "guacd"
      POSTGRES_HOSTNAME: "guacdb"
      POSTGRES_DATABASE: "${POSTGRES_NAME:-guacamole_db}"
      POSTGRES_USER: "${GUACAMOLE_DB_USER:-guacamole_db_user}"
      POSTGRES_PASSWORD: "${GUACAMOLE_DB_PASS:-weakpass}"
      # TOTP_ENABLED: "true"
    depends_on:
      - guacdb
      - guacd
    networks:
      - guacamole_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:8081
    depends_on:
      - guacamole
    networks:
      - guacamole_network

networks:
  guacamole_network:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "2a01:4f9:2b:195d::/64"

volumes:
  postgres_data: {}
